"""Profile model — user profiles linked to AWS Cognito.

The id column is the Cognito sub UUID, set by the application at registration.
It is NOT auto-generated by the database.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, CheckConstraint, DateTime, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.character import Character
    from app.models.conversation import Conversation


class Profile(TimestampMixin, Base):
    """User profile, keyed by Cognito sub UUID."""

    __tablename__ = "profiles"

    __table_args__ = (
        CheckConstraint(
            "subscription_tier IN ('free', 'premium')",
            name="ck_profiles_subscription_tier",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
    )
    email: Mapped[str] = mapped_column(Text, unique=True)
    name: Mapped[str] = mapped_column(Text)
    mem0_user_id: Mapped[str] = mapped_column(Text, unique=True)
    fcm_token: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    timezone: Mapped[str] = mapped_column(Text, default="UTC")
    avatar_url: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    preferred_language: Mapped[str] = mapped_column(Text, default="en")
    onboarding_completed: Mapped[bool] = mapped_column(Boolean, default=False)
    subscription_tier: Mapped[str] = mapped_column(Text, default="free")
    subscription_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    # Relationships — class names resolved by SQLAlchemy mapper registry
    characters: Mapped[list[Character]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
    )
    conversations: Mapped[list[Conversation]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
    )


__all__ = ["Profile"]
